### PR TITLE
Added snippets for Parameter, Parameter Types, Mapping and Output

### PR DESCRIPTION
**Pull request by sliedig**
Found these snippets quite useful when working with your library. Let me know what you think.

### CODE REVIEW

**Comment by enly1** [comment]
Hi - Will merge these shortly and thanks for the additional support.
PS - Did you run the python scripts to spider the content of create them yourself ?

**Comment by sliedig** [comment]
No worries. I really like the productivity enhancements that this projects give sublime. Happy to help. I didn't use the Python script as I wasn't sure how to run it properly, so I created them myself. Maybe some guidance on how to do that would be good?

**Comment by Narrowbeam** [comment]
The script basically was self contained - you could have probably swapped the URL for a page with the parameter details on it and it may or may not have worked - depends on the page structures, but given the number of them, I couldn't have done it by hand the first time around.

But - great job on the extras - thanks for the help !

**Comment by Narrowbeam** [comment]
Saying all of that, its not worth using my original converter any more really - a few days back, Amazon released a machine readable spec for this stuff, so we have all the data in json format, so another processor is required to convert that source into all the various formats that people need.

See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html for what I'm on about ...

**Comment by sliedig** [comment]
I saw that and I think that is a great idea. Would make updating the snippets much easier, and align it with the AWS release cycle.

**Comment by enly1** [comment]
Yes,  That was why I wrote the original scraper script so I could do the
same when they updated, but taking it from a machine readable source and
using templates for the output format for each object type would allow a
simple model for generating yaml and json snippets for a number of
ides/editors.

I've unfortunately no spare time at the moment to do it, although I'm sure
its a smaller job than the original scraping code.

One day... but would do some googling first as wouldn't surprise me if
someone had already done it.

**Pull request merged**
